tasks:
  anime:
    rss: http://www.nyaa.se/?page=rss&cats=1_37
    regexp:
      accept:
        - (.*)HorribleSubs(.*)Diabolik(.*)Lovers(.*)Blood(.*)1080(.*)
        - (.*)HorribleSubs(.*)Young(.*)Black(.*)Jack(.*)1080(.*)
        - (.*)HorribleSubs(.*)Return(.*)of(.*)Kings(.*)1080(.*)
        - (.*)HorribleSubs(.*)Noragami(.*)Aragoto(.*)1080(.*)
        - (.*)HorribleSubs(.*)Concrete(.*)Revolutio(.*)1080(.*)
        - (.*)HorribleSubs(.*)Haikyuu(.*)S2(.*)1080(.*)
        - (.*)HorribleSubs(.*)Owarimonogatari(.*)1080(.*)
        - (.*)HorribleSubs(.*)Shingeki(.*)Kyojin(.*)Chuugakkou(.*)1080(.*)
        - (.*)HorribleSubs(.*)One(.*)Punch(.*)Man(.*)1080(.*)
        - (.*)HorribleSubs(.*)High(.*)School(.*)Star(.*)Musical(.*)1080(.*)
        - (.*)HorribleSubs(.*)YuruYuri(.*)1080(.*)
        - (.*)HorribleSubs(.*)Dance(.*)with(.*)Devils(.*)1080(.*)
        - (.*)HorribleSubs(.*)Rakudai(.*)Kishi(.*)1080(.*)
        - (.*)HorribleSubs(.*)Ame(.*)iro(.*)Cocoa(.*)1080(.*)
        - (.*)HorribleSubs(.*)Hidan(.*)Aria(.*)AA(.*)1080(.*)
        - (.*)HorribleSubs(.*)Taimadou(.*)Gakuen(.*)35(.*)Shiken(.*)Shoutai(.*)1080(.*)
        - (.*)HorribleSubs(.*)Ashimoto(.*)Shitai(.*)Umatteiru(.*)1080(.*)
        - (.*)HorribleSubs(.*)Subete(.*)Naru(.*)1080(.*)
        - (.*)HorribleSubs(.*)Garo(.*)Crimson(.*)Moon(.*)1080(.*)
        - (.*)HorribleSubs(.*)Gochuumon(.*)Usagi(.*)S2(.*)1080(.*)
        - (.*)HorribleSubs(.*)Seraph(.*)End(.*)S2(.*)1080(.*)
        #Winter 2016
        - (.*)HorribleSubs(.*)Prince(.*)Stride(.*)Alternative(.*)1080(.*)
        - (.*)HorribleSubs(.*)Musaigen(.*)Phantom(.*)World(.*)1080(.*)
        - (.*)HorribleSubs(.*)Haruchika(.*)1080(.*)
        - (.*)HorribleSubs(.*)Boku(.*)Dake(.*)Machi(.*)1080(.*)
        - (.*)HorribleSubs(.*)Assassination(.*)Classroom(.*)S2(.*)1080(.*)
        - (.*)HorribleSubs(.*)Norn9(.*)1080(.*)
        - (.*)HorribleSubs(.*)Shoujo(.*)Kouya(.*)Mezasu(.*)1080(.*)
        - (.*)HorribleSubs(.*)Divine(.*)Gate(.*)1080(.*)
        - (.*)HorribleSubs(.*)Koukaku(.*)Pandora(.*)1080(.*)
        - (.*)HorribleSubs] gate(.*)1080(.*)
        - (.*)HorribleSubs(.*)Shouwa(.*)Genroku(.*)Rakugo(.*)Shinjuu(.*)1080(.*)
        - (.*)HorribleSubs(.*)Bubuki(.*)Buranki(.*)1080(.*)
        - (.*)HorribleSubs(.*)Luck(.*)Logic(.*)1080(.*)
        - (.*)HorribleSubs(.*)Durarara(.*)X2(.*)1080(.*)
        - (.*)HorribleSubs(.*)World(.*)Trigger(.*)1080(.*)
        - (.*)HorribleSubs(.*)Dimension(.*)W(.*)1080(.*)
        - (.*)HorribleSubs(.*)Nijiiro(.*)Days(.*)1080(.*)
        - (.*)HorribleSubs(.*)Hai(.*)Gensou(.*)Grimgar(.*)1080(.*)
        - (.*)HorribleSubs(.*)Dagashi(.*)Kashi(.*)1080(.*)
        - (.*)HorribleSubs(.*)Saijaku(.*)Muhai(.*)Bahamut(.*)1080(.*)
        - (.*)HorribleSubs(.*)Akagami(.*)Shirayukihime(.*)1080(.*)
        - (.*)HorribleSubs(.*)Kanata(.*)Four(.*)Rhythm(.*)1080(.*)
        - (.*)HorribleSubs(.*)Subarashii(.*)Shukufuku(.*)1080(.*)
        #Spring 2016
        - (.*)HorribleSubs(.*)Brotherhood(.*)Final(.*)Fantasy(.*)XV(.*)720(.*)
        - (.*)HorribleSubs(.*)Mayoiga(.*)1080(.*)
        - (.*)HorribleSubs(.*)Boku(.*)Hero(.*)Academia(.*)1080(.*)
        - (.*)HorribleSubs(.*)Endride(.*)1080(.*)
        - (.*)HorribleSubs(.*)Bakuon(.*)1080(.*)
        - (.*)HorribleSubs(.*)Joker(.*)Game(.*)1080(.*)
        - (.*)HorribleSubs(.*)Seisen(.*)Cerberus(.*)1080(.*)
        - (.*)HorribleSubs(.*)Re(.*)Zero(.*)kara(.*)Hajimeru(.*)Isekai(.*)Seikatsu(.*)1080(.*)
        - (.*)HorribleSubs(.*)Ushio(.*)Tora(.*)1080(.*)
        - (.*)HorribleSubs(.*)Sousei(.*)Onmyouji(.*)1080(.*)
        - (.*)HorribleSubs(.*)Super(.*)Lovers(.*)1080(.*)
        - (.*)HorribleSubs(.*)Netoge(.*)Yome(.*)Onnanoko(.*)Omotta(.*)1080(.*)
        - (.*)HorribleSubs(.*)Kabaneri(.*)Iron(.*)Fortress(.*)720(.*)
        - (.*)HorribleSubs(.*)Shounen(.*)Maid(.*)1080(.*)
        - (.*)HorribleSubs(.*)Sakamoto(.*)1080(.*)
        - (.*)HorribleSubs(.*)Kiznaiver(.*)1080(.*)
        - (.*)HorribleSubs(.*)Tanaka(.*)Itsumo(.*)Kedaruge(.*)1080(.*)
        - (.*)HorribleSubs(.*)Flying(.*)Witch(.*)1080(.*)
        - (.*)HorribleSubs(.*)Big(.*)Order(.*)1080(.*)
        #Summer2016
        - (.*)HorribleSubs(.*)Momokuri(.*)1080(.*)
        - (.*)HorribleSubs(.*)Love(.*)Live(.*)Sunshine(.*)1080(.*)
        - (.*)HorribleSubs(.*)Shokugeki(.*)Soma(.*)S2(.*)1080(.*)
        - (.*)HorribleSubs(.*)Hatsukoi(.*)Monster(.*)1080(.*)
        - (.*)HorribleSubs(.*)B(.*)Project(.*)1080(.*)
        - (.*)HorribleSubs(.*)Fukigen(.*)Mononokean(.*)1080(.*)
        - (.*)HorribleSubs(.*)Arslan(.*)Senki(.*)S2(.*)1080(.*)
        - (.*)HorribleSubs(.*)Tales(.*)Zestiria(.*)1080(.*)
        - (.*)HorribleSubs(.*)New(.*)Game(.*)1080(.*)
        - (.*)HorribleSubs(.*)Orange(.*)1080(.*)
        - (.*)HorribleSubs(.*)Cheer(.*)Danshi(.*)1080(.*)
        - (.*)HorribleSubs(.*)Gray(.*)man(.*)Hallow(.*)1080(.*)
        - (.*)HorribleSubs(.*)Servamp(.*)1080(.*)
        - (.*)HorribleSubs(.*)Taboo(.*)Tattoo(.*)1080(.*)
        - (.*)HorribleSubs(.*)Fudanshi(.*)Koukou(.*)Seikatsu(.*)1080(.*)
        - (.*)HorribleSubs(.*)Tsukiuta(.*)1080(.*)
        - (.*)HorribleSubs(.*)PRISMA(.*)3rei(.*)1080(.*)
        - (.*)HorribleSubs(.*)Binan(.*)Love(.*)S2(.*)1080(.*)
        - (.*)HorribleSubs(.*)Kono(.*)Bijutsubu(.*)Mondai(.*)1080(.*)
        - (.*)HorribleSubs(.*)Amanchu(.*)1080(.*)
        - (.*)DeadFish(.*)Aggressive(.*)Retsuko(.*)720(.*)
        - (.*)HorribleSubs(.*)Handa(.*)kun(.*)1080(.*)
        - (.*)HorribleSubs(.*)Mob(.*)Psycho(.*)100(.*)1080(.*)
        - (.*)HorribleSubs(.*)Hitori(.*)Shita(.*)Outcast(.*)1080(.*)
        - (.*)HorribleSubs(.*)Qualidea(.*)Code(.*)1080(.*)
        - (.*)HorribleSubs(.*)Battery(.*)720(.*)
        #Fall 2016
        - (.*)HorribleSubs(.*)Dream(.*)Festival(.*)1080(.*)
        - (.*)HorribleSubs(.*)Bungou(.*)Stray(.*)Dogs(.*)1080(.*)
        - (.*)HorribleSubs(.*)DAYS(.*)1080(.*)
        - (.*)HorribleSubs(.*)Nyanbo(.*)1080(.*)
        - (.*)HorribleSubs(.*)Bloodivores(.*)1080(.*)
        - (.*)HorribleSubs(.*)WWW.Working(.*)1080(.*)
        - (.*)HorribleSubs(.*)Magic(.*)Kyun(.*)Renaissance(.*)1080(.*)
      reject:
        - (.*)Batch(.*)
        - (.*)batch(.*)
    transmission:
      host: localhost
      port: 9091
    clean_transmission:
      host: localhost
      port: 9091
      tracker: nyaa
      finished_for: 10 minutes
schedules:
  - tasks: '*'
    interval:
      minutes: 5
